name: Cross platform Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v4

      - name: Cache Cargo dependencies ğŸ“¦
        uses: Swatinem/rust-cache@v2

      - name: Test ğŸ§ª
        if: matrix.os != 'windows-latest'
        run: cargo test

      - name: Build ğŸ”§
        run: cargo build --release

      - name: Add paths ğŸ“‚
        if: matrix.os != 'windows-latest'
        run: echo "::add-path::$GITHUB_WORKSPACE/target/release"

      - name: Build site ğŸ—ï¸
        if: matrix.os != 'windows-latest'
        run: marmite example site -vvvv

      - name: Build site ğŸ—ï¸
        if: matrix.os == 'windows-latest'
        run: .\target\release\marmite.exe example site -vvvv

      - name: List files on site ğŸ“‚
        if: matrix.os != 'windows-latest'
        run: ls -R site

      - name: List files on site ğŸ“‚
        if: matrix.os == 'windows-latest'
        run: dir site